### ISSUE TITLE
Why an r-spatial organisation?

### ISSUE THREAD

**Issue by edzer** [r-spatial/discuss#1]
This organisation came out of a discussion that was held in an issue of @tim-salabim 's [rspatial](https://github.com/tim-salabim/rspatial) repo, [here](https://github.com/tim-salabim/rspatial/issues/9).

**Comment by tim-salabim** [comment]
For R packages in this repo, we should probably agree on a license (in case there's no restricted third-party libraries involved). 
What are peoples' preferences?

**Comment by rsbivand** [comment]
Maybe see: [UseR! Session: Navigating the jungle of R packages.](https://stat.ethz.ch/pipermail/r-package-devel/2017q1/thread.html)
