### ISSUE TITLE
home for collecting raster fixes, discussions

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/discuss#12]
Hi, I've set up this clone of the r-forge Github mirror: 

https://github.com/mdsumner/raster-rforge

Loosely, I'm planning to craft updates to raster as PRs here, then convert them to patches for r-forge. I don't have a tight timeline for this, but the back-log of items I was thinking about was so long I needed to start writing it down. 

I guess r-spatial is a better place for this? I'd appreciate any feedback on the workflow for crafting fixes in branches, as PRs and converting them to diff patches to commit via Subversion. (I can do all that but I haven't actually exercised in this context yet). 

If there's no objections I'll just move it over. 

FYI  lots of folks have asked me about a likely update to raster, and many people have written directly to the maintainer. I'll report summaries if/when I learn any more. 

If we made a proper home it at least allows others to see what is already reported - even if we never get to a new release we can see links to workarounds and other discussions. 

----------------------------------------------------------

I'm going to continue working on "packages around the edges" of raster. I want a family of small component packages that do the key things raster does, without the monolithic all-in-one vision provided by that huge package. The main packages in this context are listed here: https://gist.github.com/mdsumner/22d057124de9790dd2615c8b1f921dc9

**Comment by pat-s** [comment]
+1!

`r-spatial` needs more attention and placing all raster fixes/ideas there until `stars` is ready is a good point to start. 

I've also written Robert but didn't get a response :/

Maybe it would also be a good idea to write a post on r-spatial.org to inform people about this campaign.

**Comment by noamross** [comment]
I think the repo should an CONTRIBUTING.md or extended section file that details the expected workflow for contributors.  Something like:

- `master` contains the current state of the package on r-forge.  Installing using `devtools` from this branch on this should be not too far from working with future CRAN releases.
- `dev` (default branch) contains the current (GitHub) development state, to be patched onto the R-forge version with some regularity.  CRAN releases from the R-forge state expected at what interval?
- Contributions should be provided as PRs to the `dev` branch.
- Open an issue/preliminary PR for discussion prior to major changes
- Some info about the scope of changes and types of PRs likely to be accepted
- Subscribe to issue No. ? for updates related to the development of the raster/stars ecosystem

**Comment by mdsumner** [comment]
Thanks!
