### ISSUE TITLE
Onboarding: RSAGA

### ISSUE THREAD

**Issue by pat-s** [r-spatial/discuss#18]
Hi guys,

we decided internally that it would be time to move [RSAGA](https://cran.r-project.org/web/packages/RSAGA/index.html) to the r-spatial org.
Unfortunately, we have no contact anymore to Donovan Bangs who maintained the Github repo for a long time: https://github.com/debangs/RSAGA.
Therefore the repo temporarly moved to https://github.com/be-marc/RSAGA for the recent 1.0.0 update (we will also create a short blog post about the changes soon).

To prevent such issues in the future, the r-spatial org seems to be the perfect place to us.
This is in accordance with the maintainer, Alexander Brenning (not on Github).

**Comment by edzer** [comment]
Great news - welcome on board, and congratulations with getting the 1.0-0 out, after 10 years!

**Comment by tim-salabim** [comment]
Sounds great! How do you want to proceed?

**Comment by pat-s** [comment]
Waiting for @be-marc to transfer ownership.

**Comment by tim-salabim** [comment]
@gisma @jannes-m @rsbivand would it make sense to also have link2GI, RQGIS and rgrass7 hosted at r-spatial? Thoughts?

**Comment by gisma** [comment]
I think it makes extremely sense to bring together the central elements (ie packages) of the R geospatial community at r-spatial. Nevertheless certainly it must be discussed  what means *central* but it means  for sure  the wrapper packages `RQGIS` and `rgrass7`. In the future even more wrapper packages  will  arise if QGIS 3.x drops parts of the processing chain support which will no longer be reached via `RQGIS` anymore. Maybe  also  ` link2GI` would be worthwhile to think abbout  though imho it is in questions of *central* only minor.
So I would very much appreciate if the authors of the packages would decide to accommodate these on r-spatial.

**Comment by rsbivand** [comment]
Sounds like a sensible idea. I already have an sf-flavoured rgrass7 [repo](https://github.com/rsbivand/rgrass7), but rgrass7 itself is still on R-forge. How should we think about CI in this context?

**Comment by tim-salabim** [comment]
@rsbivand would migrating the R-forge repo to r-spatial and having the sf flavoured code as a branch in that repo make sense?

**Comment by rsbivand** [comment]
Probably, but I'd need hand-holding wrt. creating the branch. I guess I'd do this locally first?

**Comment by tim-salabim** [comment]
Yes, when your local and remote repos are set up (linked) properly, you can create a new branch locally and simply push to remote where this new branch will then be created automatically.

**Comment by be-marc** [comment]
Hey,

thank you for accepting RSAGA. I tried to transfer the repository but I get an error message. Can you give me permission to create a repository?

**Comment by gisma** [comment]
transfer managed - thanks for taking it on r-spatial

**Comment by tim-salabim** [comment]
@be-marc I've sent you an invitation. Once you accept it you should be able to transfer the repo

**Comment by jannes-m** [comment]
I would be more than happy to integrate **RQGIS** into the r-spatial world. 
Please note that we will make **RQGIS** compatible with QGIS 3/Python 3. But we will wait a bit until the inevitable QGIS 3 first release bugs have been fixed. In any case, until at least 22. February 2019 QGIS 2.18 will be the LTR, so we still have a bit time.

**Comment by tim-salabim** [comment]
@jannes-m i've sent you an invitation. It's in your hands.

**Comment by tim-salabim** [comment]
done
