### ISSUE TITLE
intersect 4D (3D + time) trajectories with 3D volumes

### ISSUE THREAD

**Issue by espinielli** [r-spatial/discuss#21]
I am entering this issue here following https://github.com/Robinlovelace/geocompr/issues/12#issuecomment-388207258 reply to my request.

The _simple_ use case I have is about intersecting 4D (3D [lon, lat, altitude] + time) trajectories with 3D volumes, think aircraft (or drone or Uber flying cars :wink: ) flights and Air Traffic Control sectors (typically a base polygon extruded from altitude1 [possibly above ground] to altitude2).

The _more complicated_ one is where the 3D volumes do change shape in time (for example ATC sectors are collapsed during the couse of the day/night when traffic density is lower).

The _further more complicated_ case is one where you want to intersect 3D volumes moving and changing shape and intersect with other 3D volumes. Think volcanic ash cloud and ATC sectors.

I am aware of very specialized (and not in R) code for this, but would be very interested to see whether there are other domains with similar cases to further provide support in R spatial.

**Comment by tim-salabim** [comment]
Can this be closed? Given the lack of activity?

**Comment by espinielli** [comment]
Yes, unfortunately no much feedback / interest...sigh.
