### ISSUE TITLE
Onboarding: RPyGeo

### ISSUE THREAD

**Issue by be-marc** [r-spatial/discuss#22]
Hello,

we would like to move [RPyGeo](https://github.com/fapola/RPyGeo)  to r-spatial.org
We rewrote the whole package and plan to release it in a few days on CRAN.

It would be nice if you could invite @fapola, so he can transfer the ownership.

**Comment by pat-s** [comment]
@fapola Maybe its easiest to first transfer the repo to @be-marc who then can transfer it to r-spatial.

**Comment by fapola** [comment]
Sure, whatever works best for you. I will transfer the repo to @be-marc

**Comment by pat-s** [comment]
Ok cool :+1:

**Comment by fapola** [comment]
It is not possible to transfer the ownership to @be-marc: `be-marc already has a repository in the fapola/RPyGeo network`. Maybe because he already is a collaborator?!

**Comment by pat-s** [comment]
@be-marc 	Do you still have a fork in your acc? Otherwise transfer it to me and I'll do it.

**Comment by fapola** [comment]
I transferred the ownership to @pat-s.

**Comment by pat-s** [comment]
Transferred to r-spatial. Can be closed.

**Comment by pat-s** [comment]
@edzer 	@tim-salabim The following people need repo settings access for `RpyGeo` so that we can administrate the package:

- @be-marc 	
- @jannes-m 	
- @pat-s 	

Would it make sense to set up teams in the org with write permissions for dedicated repos?

PS: I think the same applies to `RSAGA`.

**Comment by edzer** [comment]
You should be all set now.
