### ISSUE TITLE
Clean up 

### ISSUE THREAD

**Issue by pat-s** [r-spatial/discuss#24]
The discussions here could be cleaned up/closed if not active anymore. I do not have rights to do this though :)

**Comment by tim-salabim** [comment]
Good point! I'll have a look through them soon

**Comment by tim-salabim** [comment]
I've cleaned up (i.e. closed isdues) as far as I felt confident.
Thanks for initiating the cleanup @pat-s 

PS: closing this, to clean up further ;-)
