### ISSUE TITLE
Why is the raster package hosted under "rspatial"?

### ISSUE THREAD

**Issue by pat-s** [r-spatial/discuss#25]
... rather than in this organisation? This looks very confusing from a user point of view.

**Comment by tim-salabim** [comment]
We know (and agree). I think @edzer has brought this up in discussions with the rspatial folks in the past. I don't know what their point of view is though

**Comment by pat-s** [comment]
Ok, thanks. Would be interesting to know, not only for me I guess :)

**Comment by edzer** [comment]
I believe we set up these two organisations independently, and sticking to the initial set up seemed easiest, merging harder.

**Comment by pat-s** [comment]
Ah, I just saw that there are even more repos. Didn't look into the org yet.
Hm, that's a pity. Quite confusing and from the outside (without this knowledge here) it may look like a "two class" r-spatial community. 

Moving repos between organization in Github works flawlessly. Are you still convinced to keep it as it is?

**Comment by edzer** [comment]
It's not about my conviction. Robert and I do a lot of similar work, mostly independently. I think moving repos is the least of our problems; the accompanying web sites r-spatial.org and rspatial.org have also developed in different directions, and a certain amount of branding has happened for both, inevitably. It would be helpful already if raster's CRAN landing page would mention the github repo in the URL: field. @rhijmans what do you think?

**Comment by tim-salabim** [comment]
I am not sure this will ever be resolved in any universally acceptable way... Shall we keep this open anyway?

**Comment by rhijmans** [comment]
rspatial on github started as a repo for rspatial.org. After that, it seemed easiest to me to add my other spatial work there as well. I understand that it may cause confusion; but I do not see a real problem; although I may not be aware of how or what people expect.

**Comment by tim-salabim** [comment]
IMO the biggest issue is with users new to spatial analysis in R. They might be recommended r(-)spatial by someone, but only see half of the picture. Which is by no means the complete R spatial picture, I am well aware of that, but strikes me as a good starting point as many things are bundeled by the two organisations. 
It might already be enough to clearly highlight the other organisation on the respective landing pages (which I have just done here).

**Comment by gisma** [comment]
I completely agree with @pat-s  comments and I'm glad he raised the topic here.

@edzer  and @rhijmans are clearly addressing this situation without beating around the bush...
> Robert and I do a lot of similar work, mostly independently 
> I understand that it may cause confusion; but I do not see a real problem; although I may not be aware of how or what people expect

Well this is quite common in communities and there is no problem at first. It is comparable to the usual process of science where x paper exists in different journals on the same topic. Much is researched and written in parallel from ignorance, disinterest or calculation. This is often annoying due to the ignorant attitude, but more often stimulating because we move forward through diversity in science.

However, if a community is about a common theme (like spatial R), the view of users and developers is usually diverse but quite convergent. Synergy effect and mutual inspiration are just as desired as efficient and transparent communication.

In particular, the lack of transparency in the communication of `r-spatial` and `r-spatial` communities makes IMO a serious problem. In my view, at least if the two branches can not be merged (for whatever reason) at least transparent be communicated. In my view, that means: (1) communicating that both exist (and are confusingly similar) and (2) communicate why they exist and how they focus. Such a text can be on CRAN or on the websites and also be coordinated together.
That should actually be possible because we all pursue very similar interests, regardless of differences, and are enthusiastic about similar things.

**Comment by pat-s** [comment]
Thanks at all first for discussing this here so lively.

Let me again make my view more clear (which should pretend a possible view from an "outside" user (not that I am one but meaning I am trying to replicate the potential thoughts of one)):

Usually repos are hosted on GH on the user level. Sometimes repo owner decide to put repos into an org because they contribute to the same purpose. This makes it easier for users to find the repos and to see that there are common efforts and discussions among the repo owner (just like for `r-spatial`). 

Now it is not uncommon that not all people want to do this and want to stay on their own. This is perfectly fine. However, if a similar organization exists, users might very well think that there is come competition going on. Or at least a reason why specific packages are in a separate organization.

I know learned that `rspatial` exists for quite some time already. However, as @rhijmans 	was not very active in there it did not really become popular. With the effors of moving `sf`, `mapview` and `stars` into `r-spatial` and @edzer, @rsbivand 	, @tim-salabim 	actively administrating the organization, it seems like an agreed effort that `r-spatial` is the organization that the "community leaders" agree on.

So far so good. Now recently the `raster` package was moved to `rspatial` form SVN (?). With this move, it became "popular" on GH and users start to raise issues. However, of course they start realizing that a different organization exists and start to question what might be the reason for it.
This is pushed by the fact that the `stars` package is informally seen as a replacement for the `raster` package by a lot of users of the spatial com in R (even though I know that @edzer 	disagreed many times). So because of this users might be pushed by thinking "oh, the maintainer from the `raster` package does not agree with what is going on in `stars` and wants to do his own thing).

Most people will just not be brave enough to ask and think "there is a reason". However, they might silently think "looks like the `raster` package maintainer does not go along well with the others". 

AFAIK this is not the case and you get along (very) well. However, this might be the subjective view from a lot of users in the community. Even pushed by the fact that the organizations have almost similar names (just differentiated by a `-`).

Of course there is no practical advantage in a possible fusion. However, please do not forget the external impact of having to splitted organizations. I would also welcome if the reason for the existence of both (if you definitely do not want to fusion them) could be outlined in a link or one sentence in the repos READMEs (however, this would possible be done for all repos then). 

Again, I want to say that this is just a POTENTIAL view from the outside. It might be different. But I just wanted to bring these thoughts into this discussion.

Thanks for your tremendous efforts for the spatial community in R @edzer 	@rhijmans 	@rsbivand 	@tim-salabim 	and others!

**Comment by edzer** [comment]
I find the best metaphor for the R community that of an ecosystem. There's [collaboration](https://twitter.com/edzerpebesma/status/960376392247476227), chaos, and competition. Imagined users drawing wrong conclusions from these two organisations on GitHub doesn't worry me. I agree that merging them might look nicer to them, but putting effort in this is relatively priority for me. If someone else wants to do this: great!

**Comment by tim-salabim** [comment]
> I find the best metaphor for the R community that of an ecosystem. There's collaboration, chaos, and competition.

All resulting in diversity. Which is usually way better than uniformity...

**Comment by edzer** [comment]
As an analogy: the [geopython](https://github.com/geopython) github organization doesn't include several popular geopython libraries like shapely, geopandas, pyproj, rasterio, etc.
