### ISSUE TITLE
Fork RStoolbox?

### ISSUE THREAD

**Issue by jl5000** [r-spatial/discuss#32]
Not sure whether this is in scope, but I've been using RStoolbox lately for calculating various indices of raster data. Might be worth forking (unless there's a package already here I've missed).

**Comment by edzer** [comment]
What would be the reason to fork it?

**Comment by jl5000** [comment]
Sorry, this many be my misunderstanding of the way you use this account. From the repo list, it looked liked relevant repos were forked for easy access. If that's not the case, feel free to close.

**Comment by tim-salabim** [comment]
To clarify, this repo/organisation is not so much about easy access, though this is one of the benefits of such a central repo, but more about collaborative package development. Most repos here are not forks AFAICT

**Comment by pat-s** [comment]
You could ask the maintainer of the package to eventually move it into the org so that we can bundle more r-spatial resources.
