### ISSUE TITLE
Transferring packages to r-spatial

### ISSUE THREAD

**Issue by florisvdh** [r-spatial/discuss#49]
Is it a sensible idea to transfer the really **_small_** `rgeopackage` package to r-spatial? To me it seems best to collect spatial packages here, but opinions may vary. Anyway I'll be happy to contribute it (on CRAN as well).

> Following helper functions to assist in writing reproducible GeoPackage files are now provided in an R package `rgeopackage` (https://github.com/florisvdh/rgeopackage).
> 
> - `preset_timestamp()`: presets the file timestamp for usage by GDAL by setting the environment variable `OGR_CURRENT_DATE`.
> - `amend_timestamp()`: overwrites timestamps in the `gpkg_contents` and `gpkg_metadata_reference` tables of an existing GeoPackage file. While directly editing a GeoPackage is not advised, this function is especially useful in the presence of the optional table `gpkg_metadata_reference`, as GDAL does not control its timestamps as of writing (for GDAL 3.1.3). See corresponding [issue](https://github.com/OSGeo/gdal/issues/3537) in the GDAL source repository.
> 
> Further ideas and contributions are welcome. Currently I have no further plans to expand the package, since it was only meant to make these specific functions available. It's not linked particularly to `sf` or another package in any way: it could theoretically assist various R packages that can write a GeoPackage, although the examples are focussed on `sf` and `stars` :wink:.
> 
> Related to `preset_timestamp()`, IMHO it would be ideal if `sf` / `stars` could themselves pass a timestamp to GDAL, so feel free to keep this issue open, or close it, depending on plans in that direction.

_Originally posted by @florisvdh in https://github.com/r-spatial/sf/issues/1618#issuecomment-807310903_

**Comment by edzer** [comment]
https://github.com/r-spatial/rgeopackage
