### ISSUE TITLE
A generic way to get osmconf.ini file

### ISSUE THREAD

**Issue by agila5** [r-spatial/discuss#66]
Dear all, 

I've created this issue since I have question regarding sf/GDAL & related tools. I'm working on an R package named [`osmextract`](https://github.com/ropensci/osmextract). A key part of the package is the management of [`.osm.pbf`](https://gdal.org/en/latest/drivers/vector/osm.html) files which, ultimately, are converted into `.gpkg` format. As described in the [GDAL page](https://gdal.org/en/latest/drivers/vector/osm.html#open-options), the details behind this conversion process are governed by a `osmconf.ini` file. For example, this is the file currently used by GDAL: https://raw.githubusercontent.com/OSGeo/gdal/refs/heads/master/ogr/ogrsf_frmts/osm/data/osmconf.ini

The behaviour curently used by `osmextract` package is to store a fixed version of that file (https://raw.githubusercontent.com/ropensci/osmextract/refs/heads/master/inst/osmconf.ini) and modify it whenever is needed or required by a user. This is partly unsatisfactory since 1) I need to update it whenever there is a change "upstream" and 2) I would like to always "match" the osmconf.ini file with its GDAL version. So I was wondering: is there a generic and "universal" way that points to the location of that file? 

For example, on Windows that file is simply stored in the directory where `sf` is installed: 

``` r
list.files(
  system.file(package = "sf"), 
  "osmconf", 
  recursive = TRUE
)
#> [1] "gdal/osmconf.ini"
```

<sup>Created on 2024-11-07 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.1 (2023-06-16 ucrt)
#>  os       Windows 11 x64 (build 22631)
#>  system   x86_64, mingw32
#>  ui       RTerm
#>  language (EN)
#>  collate  English_United Kingdom.utf8
#>  ctype    English_United Kingdom.utf8
#>  tz       Europe/Rome
#>  date     2024-11-07
#>  pandoc   3.2 @ C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date (UTC) lib source
#>  cli           3.6.3.9000 2024-10-22 [1] Github (r-lib/cli@38cef38)
#>  digest        0.6.37     2024-08-19 [1] CRAN (R 4.3.1)
#>  evaluate      0.24.0     2024-06-10 [1] CRAN (R 4.3.3)
#>  fastmap       1.2.0      2024-05-15 [1] CRAN (R 4.3.3)
#>  fs            1.6.4      2024-04-25 [1] CRAN (R 4.3.3)
#>  glue          1.7.0      2024-01-09 [1] CRAN (R 4.3.2)
#>  htmltools     0.5.8.1    2024-04-04 [1] CRAN (R 4.3.3)
#>  knitr         1.48       2024-07-07 [1] CRAN (R 4.3.1)
#>  lifecycle     1.0.4      2023-11-07 [1] CRAN (R 4.3.2)
#>  magrittr      2.0.3      2022-03-30 [1] CRAN (R 4.3.1)
#>  purrr         1.0.2      2023-08-10 [1] CRAN (R 4.3.1)
#>  R.cache       0.16.0     2022-07-21 [1] CRAN (R 4.3.1)
#>  R.methodsS3   1.8.2      2022-06-13 [1] CRAN (R 4.3.1)
#>  R.oo          1.25.0     2022-06-12 [1] CRAN (R 4.3.1)
#>  R.utils       2.12.2     2022-11-11 [1] CRAN (R 4.3.1)
#>  reprex        2.0.2      2022-08-17 [1] CRAN (R 4.3.1)
#>  rlang         1.1.4      2024-06-04 [1] CRAN (R 4.3.1)
#>  rmarkdown     2.28       2024-08-17 [1] CRAN (R 4.3.1)
#>  rstudioapi    0.16.0     2024-03-24 [1] CRAN (R 4.3.1)
#>  sessioninfo   1.2.2      2021-12-06 [1] CRAN (R 4.3.1)
#>  styler        1.10.2     2023-08-29 [1] CRAN (R 4.3.1)
#>  vctrs         0.6.5      2023-12-01 [1] CRAN (R 4.3.2)
#>  withr         3.0.1      2024-07-31 [1] CRAN (R 4.3.3)
#>  xfun          0.45       2024-06-16 [1] CRAN (R 4.3.3)
#>  yaml          2.3.9      2024-07-05 [1] CRAN (R 4.3.3)
#> 
#>  [1] C:/Users/user/AppData/Local/R/win-library/4.3
#>  [2] C:/Program Files/R/R-4.3.1/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

whereas, AFAICT, the same doesn't work on Ubuntu system: 

``` r
list.files(system.file(package = "sf"), "osmconf", recursive = TRUE)
#> character(0)
```

**Comment by edzer** [comment]
OSX and Windows CRAN binary installs will work with your method above, platforms where `sf` is compiled from source will have `gdal-config`, which gives for instance
```bash
$ gdal-config --datadir
/usr/share/gdal
```
which users may override by setting the environment variable `GDAL_DATA`.

**Comment by agila5** [comment]
Thank you very much @edzer 🙇‍♂️
