### ISSUE TITLE
Compilation of all r-spatial related websites

### ISSUE THREAD

**Issue by pat-s** [r-spatial/discuss#8]
On the [official R website](https://www.r-project.org/other-projects.html), there is a section on "Rgeo: Spatial Statistics with R" which lists all websites dealing with r-spatial stuff (just discovered it for me)

Shouldn't´t we link the following sites there? (Probably there are a lot more)

- http://www.rspatial.org
- http://r-spatial.org
- https://github.com/r-spatial

**Comment by tim-salabim** [comment]
Some sort of resource overview for R spatial stuff would surely be nice, but I don't thin that this repo is a good place for it.... Let me know if you disagree
