### ISSUE TITLE
discussion on topology ...

### ISSUE THREAD

**Issue by mdsumner** [r-spatial/discuss#9]
@cyrus621 very keen to chat with you about this if you don't mind? I'm interested in anything on the history of "the end of topology", terminology that was used at the time, key events, and discussions that were had. Are you happy to discuss here? 

Previously thoughts here: 

https://github.com/edzer/sfr/issues/252#issuecomment-285074690

https://github.com/r-spatial/rspatial_spark/issues/3

I want to see if my summary under "Why?" here rings true, and to flesh out the history pre-ArcView and so on: 

https://github.com/mdsumner/sc

**Comment by cyrus621** [comment]
Mr Sumner,

I am just a humble user of spatial information, I am not able to participate in the deeper discussions of how spatial data should be ideally organized. My comment was only about my confusion when ESRI suddenly dropped all their promotion of the correct topology in coverages (which was one of their big “selling points” in ArcINFO) and introduced shapefiles, which as I understand it (and I am not an expert) do not have full topology as part of the structure.

So I can’t be of any further help to you. I will follow your developments with interest, however.

Regards,

Rossiter, D G (David)
Guest Researcher
ISRIC - World Soil Information
david.rossiter@wur.nl<mailto:david.rossiter@wur.nl>





On 09 Mar 2017, at 04:31, Michael Sumner <notifications@github.com<mailto:notifications@github.com>> wrote:


@cyrus621<https://github.com/cyrus621> very keen to chat with you about this if you don't mind? I'm interested in anything on the history of "the end of topology", terminology that was used at the time, key events, and discussions that were had. Are you happy to discuss here?

Previously thoughts here:

edzer/sfr#252 (comment)<https://github.com/edzer/sfr/issues/252#issuecomment-285074690>

r-spatial/rspatial_spark#3<https://github.com/r-spatial/rspatial_spark/issues/3>

I want to see if my summary under "Why?" here rings true, and to flesh out the history pre-ArcView and so on:

https://github.com/mdsumner/sc

**Comment by mdsumner** [comment]
Hi, no worries that is helpful though, exactly those perspectives that there was a "drop in the marketing" spiel at the time. One of the things I'm interested in finding is any discussion on how challenging triangulation of polygons was, and whether that was discussed anywhere. 

Thanks for replying!  If you know of any related discussions I'd be interested.
